### ISSUE TITLE
cure.lic setup opens too tall for many displays, cannot be resized, and often makes the "Save" button inaccessible

### ISSUE THREAD

**Issue by ChickenBeard** [elanthia-online/gtk3-scripts#33]
Any attempt to resize (dragging edges, double-clicking title bar, etc). keep the bottom of the window out of visibility. 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/4358797/132439890-07810a10-d3b0-4dbe-b77b-8f0dfb6ebb78.png">

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/4358797/132439908-6f533ebc-d65d-4cfa-a389-39c8c551ce73.png">

**Comment by OSXLich-Doug** [comment]
Closed with updated cure.
